on:
  push:
  pull_request:

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Étape spécifique à Linux pour installer GTK+ 3
      - name: Install dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev build-essential pkg-config

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.pub-cache
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Build devs cleaner backend
        working-directory: ./devs_cleaner
        run: cargo build --release

      - name: Build Flutter macos app
        working-directory: ./build_buster
        if: ${{ matrix.os == 'macos-latest' }}
        run: flutter build macos --release

      - name: Build Flutter windows app
        working-directory: ./build_buster
        if: ${{ matrix.os == 'windows-latest' }}
        run: flutter build windows --release

      - name: Build Flutter linux app
        working-directory: ./build_buster
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: flutter build linux --release

      - name: Prepare run scripts Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mkdir -p scripts/bin
          copy devs_cleaner\target\release\devs_cleaner scripts\bin\devs_cleaner
          copy build_buster\build\windows\x64\runner\Release\build_buster.exe scripts\bin\build_buster.exe
          

      - name: Prepare run scripts Ubuntu and MacOS
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p scripts/bin
          cp devs_cleaner/target/release/devs_cleaner scripts/bin/devs_cleaner
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            cp -r build_buster/build/macos/Build/Products/Release/build_buster.app scripts/bin/build_buster.app
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cp -r build_buster/build/linux/x64/release/bundle/build_buster scripts/bin/build_buster
          fi

      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build_buster-${{ matrix.os }}
          path: |
            scripts/bin/devs_cleaner
            scripts/bin/build_buster*
            scripts/run-*.sh
            